/* ============================================================
 * K-Riders 스팟 DB — CSV/폼 공용 검증 모듈 (Phase 0 · 4단계).
 *   단일 기준: types.ts(필드 사전) + constants.ts(enum 배열·검증 상수)를
 *   import 해서 쓴다 — 여기서 기준값을 재정의하지 않는다.
 *   순수 모듈: Node API(fs/path/process) 사용 금지 — 5단계 모바일
 *   수집 폼(클라이언트)과 scripts/validate-spots.ts CLI 가 함께 쓴다.
 *
 *   [결정 기록 — 하버사인] lib/motorcycle/rideEstimate.ts 의 straightKm 을
 *   import 하지 않고 동일 수식을 자체 구현한다. 이유: (1) 좌표 필드 형태
 *   (latitude/longitude vs lat/lng)와 단위(km vs m)가 달라 import 하면
 *   변환 래퍼만 늘어나고, (2) spots 모듈은 폼·CLI 어디서든 단독 import
 *   가능한 순수 모듈로 유지해 다른 도메인 모듈에 의존하지 않는다.
 *   수식은 straightKm 과 동일(지구 반지름만 미터 단위).
 * ============================================================ */

import type {
  NewSpot,
  SpotCategory,
  SpotSource,
  RoadSurface,
  ParkingMoto,
  CrowdWeekend,
  BestTime,
  SpotStatus,
} from "./types";
import {
  SPOT_CATEGORIES,
  SPOT_SOURCES,
  ROAD_SURFACES,
  PARKING_MOTO_LEVELS,
  CROWD_WEEKEND_LEVELS,
  BEST_TIMES,
  SPOT_STATUSES,
  WINDING_GRADE_MIN,
  WINDING_GRADE_MAX,
  RATING_PERSONAL_MIN,
  RATING_PERSONAL_MAX,
  BEST_SEASON_MONTH_MIN,
  BEST_SEASON_MONTH_MAX,
  KOREA_LAT_MIN,
  KOREA_LAT_MAX,
  KOREA_LNG_MIN,
  KOREA_LNG_MAX,
  DUPLICATE_RADIUS_M,
} from "./constants";

/* ── CSV 컬럼 사전 ─────────────────────────────────────────── */

/** CSV 템플릿 컬럼(순서 포함) — 필드 사전 전체에서 id/created_at/updated_at 제외.
 *  data/spots-template.csv 헤더와 1:1 동기화(한쪽만 수정 금지). */
export const SPOT_CSV_COLUMNS = [
  "name",
  "category",
  "lat",
  "lng",
  "region_sido",
  "source",
  "slug",
  "alt_name",
  "tags",
  "address_road",
  "region_sigungu",
  "access_note",
  "road_surface",
  "parking_moto",
  "winding_grade",
  "senior_friendly",
  "photo_spot",
  "photo_note",
  "best_season",
  "best_time",
  "stay_minutes",
  "crowd_weekend",
  "rating_personal",
  "verified",
  "source_url",
  "memo",
  "photos",
  "status",
] as const;

/** 필수 6필드. */
export const SPOT_REQUIRED_FIELDS = [
  "name",
  "category",
  "lat",
  "lng",
  "region_sido",
  "source",
] as const;

/* ── 타입 ──────────────────────────────────────────────────── */

export interface SpotValidationError {
  /** 사람 기준 행 번호 — 헤더가 1행, 데이터는 2행부터. */
  row: number;
  field?: string;
  /** 한국어 사유. */
  reason: string;
}

/** 파싱 직후의 느슨한 행 — enum 필드는 아직 string(검증 전).
 *  필수 필드도 optional 로 두고 validateSpotRow 가 누락을 잡는다. */
export interface SpotCandidate {
  name?: string;
  category?: string;
  lat?: number;
  lng?: number;
  region_sido?: string;
  source?: string;
  slug?: string;
  alt_name?: string;
  tags?: string[];
  address_road?: string;
  region_sigungu?: string;
  access_note?: string;
  road_surface?: string;
  parking_moto?: string;
  winding_grade?: number;
  senior_friendly?: boolean;
  photo_spot?: boolean;
  photo_note?: string;
  best_season?: number[];
  best_time?: string[];
  stay_minutes?: number;
  crowd_weekend?: string;
  rating_personal?: number;
  verified?: boolean;
  source_url?: string;
  memo?: string;
  photos?: string[];
  status?: string;
}

/** 기존 DB 스팟과의 교차 중복 검사에 필요한 최소 필드. */
export interface ExistingSpotRef {
  name: string;
  lat: number;
  lng: number;
  slug?: string | null;
}

export interface SpotRowContext {
  existing?: readonly ExistingSpotRef[];
}

/** 검증 통과 행 — slug 는 자동 생성 포함 항상 채워진다. */
export interface ValidatedSpotRow {
  /** 사람 기준 행 번호(헤더=1행). */
  row: number;
  spot: NewSpot & { slug: string };
  /** CSV 의 slug 칸이 비어 있어 자동 생성됐는지. */
  slugAutoGenerated: boolean;
}

export interface SpotValidationResult {
  valid: ValidatedSpotRow[];
  errors: SpotValidationError[];
}

/* ── slug ──────────────────────────────────────────────────── */

/** slug 허용 형식 — 소문자 라틴/숫자/한글 토큰을 하이픈으로 연결. */
const SLUG_PATTERN = /^[a-z0-9가-힣]+(?:-[a-z0-9가-힣]+)*$/;

/** slug 자동 생성 — 한글 유지 + 하이픈 방식(레포에 로마자 변환 선례 없음).
 *  name+"-"+region_sido 기반: 라틴만 소문자화, 공백·특수문자는 하이픈으로,
 *  연속 하이픈 축약, 앞뒤 하이픈 제거.
 *  예: ("카페 언덕집", "경북") → "카페-언덕집-경북". */
export function slugifySpot(name: string, regionSido: string): string {
  return `${name} ${regionSido}`
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** 행의 최종 slug — 채워져 있으면 그 값, 비어 있으면 자동 생성.
 *  자동 생성이 빈 문자열이 되면(이름이 전부 특수문자 등) undefined. */
export function effectiveSlugOf(candidate: SpotCandidate): string | undefined {
  if (candidate.slug) return candidate.slug;
  if (candidate.name && candidate.region_sido) {
    const auto = slugifySpot(candidate.name, candidate.region_sido);
    return auto || undefined;
  }
  return undefined;
}

/* ── 거리 ──────────────────────────────────────────────────── */

/** 두 좌표 간 하버사인 거리(미터) — 중복 판정(DUPLICATE_RADIUS_M) 기준.
 *  rideEstimate.straightKm 과 동일 수식(파일 상단 결정 기록 참조). */
export function haversineM(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number }
): number {
  const R = 6371000;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}

/* ── CSV 문자열 → 타입 변환 ────────────────────────────────── */

const TRUE_WORDS = new Set(["true", "1", "예", "yes", "y"]);
const FALSE_WORDS = new Set(["false", "0", "아니오", "no", "n"]);

/** CSV 리스트 구분자 — CSV 자체 구분자(쉼표)와 충돌하지 않도록 세미콜론.
 *  tags/photos/best_season/best_time 공통(가이드 문서에 명시). */
export const CSV_LIST_SEPARATOR = ";";

/** CSV 원시 행(문자열 값) → SpotCandidate 변환.
 *  - 빈 문자열은 undefined(미입력) 처리
 *  - 리스트는 세미콜론(;) 구분, boolean 은 true/false/1/0/예/아니오 허용
 *  - 변환 불가 값은 errors 로 수집(rowNumber 는 사람 기준 행 번호). */
export function parseCsvSpotRow(
  raw: Record<string, string>,
  rowNumber = 0
): { candidate: SpotCandidate; errors: SpotValidationError[] } {
  const errors: SpotValidationError[] = [];

  const str = (field: string): string | undefined => {
    const v = raw[field];
    const t = typeof v === "string" ? v.trim() : "";
    return t ? t : undefined;
  };
  const num = (field: string): number | undefined => {
    const t = str(field);
    if (t === undefined) return undefined;
    const v = Number(t);
    if (!Number.isFinite(v)) {
      errors.push({ row: rowNumber, field, reason: `숫자가 아닙니다: '${t}'` });
      return undefined;
    }
    return v;
  };
  const bool = (field: string): boolean | undefined => {
    const t = str(field);
    if (t === undefined) return undefined;
    const w = t.toLowerCase();
    if (TRUE_WORDS.has(w)) return true;
    if (FALSE_WORDS.has(w)) return false;
    errors.push({
      row: rowNumber,
      field,
      reason: `불리언이 아닙니다: '${t}' (허용: true/false/1/0/예/아니오)`,
    });
    return undefined;
  };
  const list = (field: string): string[] | undefined => {
    const t = str(field);
    if (t === undefined) return undefined;
    const items = t
      .split(CSV_LIST_SEPARATOR)
      .map((x) => x.trim())
      .filter(Boolean);
    return items.length > 0 ? items : undefined;
  };
  const numList = (field: string): number[] | undefined => {
    const items = list(field);
    if (items === undefined) return undefined;
    const out: number[] = [];
    for (const item of items) {
      const v = Number(item);
      if (!Number.isFinite(v)) {
        errors.push({
          row: rowNumber,
          field,
          reason: `숫자가 아닌 항목: '${item}' (세미콜론(;) 구분 — 예: 4;5;10)`,
        });
        continue;
      }
      out.push(v);
    }
    return out;
  };

  const candidate: SpotCandidate = {
    name: str("name"),
    category: str("category"),
    lat: num("lat"),
    lng: num("lng"),
    region_sido: str("region_sido"),
    source: str("source"),
    slug: str("slug"),
    alt_name: str("alt_name"),
    tags: list("tags"),
    address_road: str("address_road"),
    region_sigungu: str("region_sigungu"),
    access_note: str("access_note"),
    road_surface: str("road_surface"),
    parking_moto: str("parking_moto"),
    winding_grade: num("winding_grade"),
    senior_friendly: bool("senior_friendly"),
    photo_spot: bool("photo_spot"),
    photo_note: str("photo_note"),
    best_season: numList("best_season"),
    best_time: list("best_time"),
    stay_minutes: num("stay_minutes"),
    crowd_weekend: str("crowd_weekend"),
    rating_personal: num("rating_personal"),
    verified: bool("verified"),
    source_url: str("source_url"),
    memo: str("memo"),
    photos: list("photos"),
    status: str("status"),
  };

  return { candidate, errors };
}

/* ── 행 단위 검증 ──────────────────────────────────────────── */

/** 단일 행 검증 — 필수/enum/좌표 범위/등급 범위/slug 형식 + (context.existing
 *  이 있으면) 기존 스팟과의 이름·100m·slug 중복까지. 파일 내 상호 중복은
 *  행 단위로는 알 수 없으므로 validateSpots 가 담당한다. */
export function validateSpotRow(
  candidate: SpotCandidate,
  rowNumber: number,
  context?: SpotRowContext
): SpotValidationError[] {
  const errors: SpotValidationError[] = [];
  const push = (field: string | undefined, reason: string) =>
    errors.push({ row: rowNumber, field, reason });

  // ① 필수 6필드
  if (!candidate.name) push("name", "필수 필드가 비어 있습니다");
  if (!candidate.category) push("category", "필수 필드가 비어 있습니다");
  if (candidate.lat === undefined) push("lat", "필수 필드가 비어 있습니다");
  if (candidate.lng === undefined) push("lng", "필수 필드가 비어 있습니다");
  if (!candidate.region_sido) push("region_sido", "필수 필드가 비어 있습니다");
  if (!candidate.source) push("source", "필수 필드가 비어 있습니다");

  // ② enum 값 유효성 — constants.ts 배열과 대조
  const enumCheck = (
    field: string,
    value: string | undefined,
    allowed: readonly string[]
  ) => {
    if (value !== undefined && !allowed.includes(value)) {
      push(field, `허용되지 않은 값 '${value}' — 허용: ${allowed.join(", ")}`);
    }
  };
  enumCheck("category", candidate.category, SPOT_CATEGORIES);
  enumCheck("source", candidate.source, SPOT_SOURCES);
  enumCheck("road_surface", candidate.road_surface, ROAD_SURFACES);
  enumCheck("parking_moto", candidate.parking_moto, PARKING_MOTO_LEVELS);
  enumCheck("crowd_weekend", candidate.crowd_weekend, CROWD_WEEKEND_LEVELS);
  enumCheck("status", candidate.status, SPOT_STATUSES);
  for (const t of candidate.best_time ?? []) {
    enumCheck("best_time", t, BEST_TIMES);
  }

  // ③ 좌표 한국 범위
  if (
    candidate.lat !== undefined &&
    (candidate.lat < KOREA_LAT_MIN || candidate.lat > KOREA_LAT_MAX)
  ) {
    push(
      "lat",
      `위도 ${candidate.lat} — 한국 범위(${KOREA_LAT_MIN}~${KOREA_LAT_MAX})를 벗어났습니다 (좌표 오타 의심)`
    );
  }
  if (
    candidate.lng !== undefined &&
    (candidate.lng < KOREA_LNG_MIN || candidate.lng > KOREA_LNG_MAX)
  ) {
    push(
      "lng",
      `경도 ${candidate.lng} — 한국 범위(${KOREA_LNG_MIN}~${KOREA_LNG_MAX})를 벗어났습니다 (좌표 오타 의심)`
    );
  }

  // ④ 등급/월/체류시간 범위
  const intRange = (
    field: string,
    value: number | undefined,
    min: number,
    max: number
  ) => {
    if (value === undefined) return;
    if (!Number.isInteger(value) || value < min || value > max) {
      push(field, `${min}~${max} 사이 정수여야 합니다 (입력값: ${value})`);
    }
  };
  intRange("winding_grade", candidate.winding_grade, WINDING_GRADE_MIN, WINDING_GRADE_MAX);
  intRange(
    "rating_personal",
    candidate.rating_personal,
    RATING_PERSONAL_MIN,
    RATING_PERSONAL_MAX
  );
  for (const m of candidate.best_season ?? []) {
    if (!Number.isInteger(m) || m < BEST_SEASON_MONTH_MIN || m > BEST_SEASON_MONTH_MAX) {
      push(
        "best_season",
        `월은 ${BEST_SEASON_MONTH_MIN}~${BEST_SEASON_MONTH_MAX} 사이 정수여야 합니다 (입력값: ${m})`
      );
    }
  }
  if (
    candidate.stay_minutes !== undefined &&
    (!Number.isInteger(candidate.stay_minutes) || candidate.stay_minutes <= 0)
  ) {
    push("stay_minutes", `0보다 큰 정수(분)여야 합니다 (입력값: ${candidate.stay_minutes})`);
  }

  // ⑥ slug 형식(채워져 있을 때만 — 자동 생성분은 생성 규칙상 항상 유효)
  if (candidate.slug !== undefined && !SLUG_PATTERN.test(candidate.slug)) {
    push(
      "slug",
      `형식 오류 '${candidate.slug}' — 소문자 영문/숫자/한글을 하이픈(-)으로 연결한 형태여야 합니다 (예: 카페-언덕집-경북)`
    );
  }

  // ⑤·⑥ 기존 스팟과의 교차 중복(이름/100m/slug)
  const existing = context?.existing ?? [];
  if (existing.length > 0) {
    const name = candidate.name;
    const slug = effectiveSlugOf(candidate);
    const hasCoords = candidate.lat !== undefined && candidate.lng !== undefined;
    for (const e of existing) {
      if (name && e.name.trim() === name) {
        push("name", `기존 DB 스팟 '${e.name}' 과(와) 이름이 동일합니다 (중복)`);
      }
      if (hasCoords) {
        const d = haversineM(
          { lat: candidate.lat as number, lng: candidate.lng as number },
          { lat: e.lat, lng: e.lng }
        );
        if (d <= DUPLICATE_RADIUS_M) {
          push(
            undefined,
            `기존 DB 스팟 '${e.name}' 과(와) ${Math.round(d)}m 거리 — ${DUPLICATE_RADIUS_M}m 이내 중복 의심`
          );
        }
      }
      if (slug && e.slug && e.slug === slug) {
        push("slug", `기존 DB 스팟 '${e.name}' 의 slug '${e.slug}' 와(과) 충돌합니다`);
      }
    }
  }

  return errors;
}

/* ── 집계 검증 ─────────────────────────────────────────────── */

/** CSV 원시 행 배열 전체 검증 — 행 단위(parse+validateSpotRow) + 파일 내
 *  상호 중복(이름/100m/slug) + (existing 전달 시) 기존 스팟 교차 중복.
 *  행 번호는 사람 기준: 헤더=1행, 데이터는 2행부터. */
export function validateSpots(
  rawRows: readonly Record<string, string>[],
  existing?: readonly ExistingSpotRef[]
): SpotValidationResult {
  const errors: SpotValidationError[] = [];
  const rows: { rowNumber: number; candidate: SpotCandidate; hasError: boolean }[] = [];

  rawRows.forEach((raw, i) => {
    const rowNumber = i + 2; // 헤더=1행, 데이터=2행부터
    const { candidate, errors: parseErrors } = parseCsvSpotRow(raw, rowNumber);
    // 파싱 실패한 필드는 "필수 누락" 재보고하지 않는다(이중 에러 방지)
    const parsedErrorFields = new Set(parseErrors.map((e) => e.field));
    const rowErrors = validateSpotRow(candidate, rowNumber, { existing }).filter(
      (e) => !(e.field && parsedErrorFields.has(e.field))
    );
    const all = [...parseErrors, ...rowErrors];
    errors.push(...all);
    rows.push({ rowNumber, candidate, hasError: all.length > 0 });
  });

  // 파일 내 상호 중복 — 이름(트림 후 완전일치) / slug (뒤 행에 에러)
  const nameFirstRow = new Map<string, number>();
  const slugFirstRow = new Map<string, { row: number; name: string }>();
  for (const r of rows) {
    const name = r.candidate.name;
    if (name) {
      const first = nameFirstRow.get(name);
      if (first !== undefined) {
        errors.push({
          row: r.rowNumber,
          field: "name",
          reason: `${first}행과 이름 '${name}' 이(가) 동일합니다 (파일 내 중복)`,
        });
        r.hasError = true;
      } else {
        nameFirstRow.set(name, r.rowNumber);
      }
    }
    const slug = effectiveSlugOf(r.candidate);
    if (slug) {
      const first = slugFirstRow.get(slug);
      if (first) {
        errors.push({
          row: r.rowNumber,
          field: "slug",
          reason: `${first.row}행('${first.name}')과 slug '${slug}' 이(가) 충돌합니다 (파일 내 중복)`,
        });
        r.hasError = true;
      } else {
        slugFirstRow.set(slug, { row: r.rowNumber, name: name ?? "" });
      }
    }
  }

  // 파일 내 상호 중복 — 100m 이내 좌표(하버사인, 뒤 행에 에러)
  for (let i = 0; i < rows.length; i++) {
    const a = rows[i].candidate;
    if (a.lat === undefined || a.lng === undefined) continue;
    for (let j = i + 1; j < rows.length; j++) {
      const b = rows[j].candidate;
      if (b.lat === undefined || b.lng === undefined) continue;
      const d = haversineM({ lat: a.lat, lng: a.lng }, { lat: b.lat, lng: b.lng });
      if (d <= DUPLICATE_RADIUS_M) {
        errors.push({
          row: rows[j].rowNumber,
          reason: `${rows[i].rowNumber}행 '${a.name ?? "?"}' 과(와) ${Math.round(d)}m 거리 — ${DUPLICATE_RADIUS_M}m 이내 중복 의심`,
        });
        rows[j].hasError = true;
      }
    }
  }

  // 에러 0개 행만 NewSpot 으로 승격(slug 는 자동 생성 포함 항상 채움)
  const valid: ValidatedSpotRow[] = [];
  for (const r of rows) {
    if (r.hasError) continue;
    const c = r.candidate;
    const slug = effectiveSlugOf(c);
    if (!slug) {
      errors.push({
        row: r.rowNumber,
        field: "slug",
        reason: "slug 자동 생성 실패 — name/region_sido 에 사용할 수 있는 문자가 없습니다",
      });
      continue;
    }
    valid.push({
      row: r.rowNumber,
      slugAutoGenerated: !c.slug,
      spot: {
        // 필수 6필드 — hasError=false 이므로 존재가 보장된다
        name: c.name as string,
        category: c.category as SpotCategory,
        lat: c.lat as number,
        lng: c.lng as number,
        region_sido: c.region_sido as string,
        source: c.source as SpotSource,
        slug,
        alt_name: c.alt_name,
        tags: c.tags,
        address_road: c.address_road,
        region_sigungu: c.region_sigungu,
        access_note: c.access_note,
        road_surface: c.road_surface as RoadSurface | undefined,
        parking_moto: c.parking_moto as ParkingMoto | undefined,
        winding_grade: c.winding_grade,
        senior_friendly: c.senior_friendly,
        photo_spot: c.photo_spot,
        photo_note: c.photo_note,
        best_season: c.best_season,
        best_time: c.best_time as BestTime[] | undefined,
        stay_minutes: c.stay_minutes,
        crowd_weekend: c.crowd_weekend as CrowdWeekend | undefined,
        rating_personal: c.rating_personal,
        verified: c.verified,
        source_url: c.source_url,
        memo: c.memo,
        photos: c.photos,
        status: c.status as SpotStatus | undefined,
      },
    });
  }

  return { valid, errors };
}
