/* ============================================================
 * K-Riders 스팟 DB — 어드민 목록/등록 API (Phase 0 · 5단계).
 *   GET  : 토큰 게이트 → motorcycle_spots 전체 목록(최신순).
 *          서버 필터 없음 — 100~수백 건 규모라 전량 반환이 단순하고,
 *          필터는 클라이언트(목록 화면 칩)가 담당한다.
 *   POST : 토큰 게이트 → 스팟 1건 검증(validate.ts 재사용, 기존 스팟
 *          교차 중복 포함) → insert. slug 비면 자동 생성.
 *   service role 은 이 파일(과 형제 route)에서만 — 클라이언트 노출 금지.
 * ============================================================ */

import { NextResponse } from "next/server";
import { getSupabaseAdminClient } from "@/lib/data/supabaseAdmin";
import { validateSpots } from "@/lib/motorcycle/spots/validate";
import {
  SPOTS_TABLE,
  badRequestBody,
  fetchExistingRefs,
  readRawRecord,
  serviceRoleMissingResponse,
  spotToRow,
  tokenGate,
  validationFailedResponse,
} from "./_shared";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const gate = tokenGate(request);
  if (gate) return gate;

  const admin = getSupabaseAdminClient();
  if (!admin) return serviceRoleMissingResponse();

  const { data, error } = await admin
    .from(SPOTS_TABLE)
    .select("*")
    .order("created_at", { ascending: false });

  if (error) {
    console.error("[admin/spots] select failed:", error.message);
    return NextResponse.json(
      { error: "query_failed", message: "스팟 목록 조회에 실패했습니다. 잠시 후 다시 시도해 주세요." },
      { status: 500 }
    );
  }

  return NextResponse.json({
    spots: data ?? [],
    generatedAt: new Date().toISOString(),
  });
}

export async function POST(request: Request) {
  const gate = tokenGate(request);
  if (gate) return gate;

  const admin = getSupabaseAdminClient();
  if (!admin) return serviceRoleMissingResponse();

  const raw = await readRawRecord(request);
  if (!raw) return badRequestBody();

  // 기존 스팟 전체와 교차 중복 검사(이름/100m 좌표/slug) — validate.ts 기준.
  const existing = await fetchExistingRefs(admin);
  if ("errorResponse" in existing) return existing.errorResponse;

  const { valid, errors } = validateSpots([raw], existing.refs);
  if (errors.length > 0 || valid.length === 0) {
    return validationFailedResponse(errors);
  }

  const row = spotToRow(valid[0].spot);
  const { data, error } = await admin.from(SPOTS_TABLE).insert(row).select().single();

  if (error) {
    console.error("[admin/spots] insert failed:", error.message);
    // 23505 = unique 위반(slug partial unique) — 검증 통과 후 동시 등록 경합.
    if (error.code === "23505") {
      return NextResponse.json(
        {
          error: "conflict",
          message: "같은 slug 의 스팟이 방금 등록됐습니다 — 목록을 새로고침한 뒤 다시 시도해 주세요.",
        },
        { status: 409 }
      );
    }
    return NextResponse.json(
      { error: "insert_failed", message: "스팟 등록에 실패했습니다. 잠시 후 다시 시도해 주세요." },
      { status: 500 }
    );
  }

  return NextResponse.json(
    { spot: data, slugAutoGenerated: valid[0].slugAutoGenerated },
    { status: 201 }
  );
}
